disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

line_length:
  warning: 125
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - x
    - y
    - dx
    - dy
    - i
    - j
    - k
    - vm

nesting:
  type_level:
    warning: 3
    error: 5

custom_rules:
  explicit_view_store_property:
    name: "Explicit ViewStore Property"
    regex: '@StateObject|@ObservedObject|@Published'
    message: "ViewStore properties should be explicitly declared"
    severity: warning

excluded:
  - Pods
  - .build
  - DerivedData
  - fastlane
  - vendor
  - Carthage
  - Generated
